# Generated by Django 5.0.4 on 2024-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.CharField(choices=[('Dinesh Bhaiya', 'Dinesh Bhaiya'), ('Anita Tai', 'Anita Tai'), ('Rohit Sir', 'Rohit Sir'), ('Priya Madam', 'Priya Madam'), ('Vijay Master', 'Vijay Master')], max_length=50),
        ),
    ]
