# Generated by Django 5.0.4 on 2024-07-06 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_alter_member_name_alter_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='member',
            name='encrypted_barcode_data',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
