# Generated by Django 5.0.4 on 2024-07-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_remove_member_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
