# Generated by Django 5.0.4 on 2024-07-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_invoice_whatsapp_sent_alter_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='Default value', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
